#include "shell.h"

/**
 * free_args - Frees the tokens generated by tokenizer.c
 *
 * @args: Tokens to be free'd
 *
 * Return: NOTHING!!! [SUCCESS]
 */

void free_args(char **args)
{
	int i = 0;

	for (; args[i] != NULL; i++)
	{
		free(args[i]);
	}
}
